### ISSUE TITLE
Bold `Statement` by default?

### ISSUE THREAD

**Issue by Pokryton** [blazkowolf/gruber-darker.nvim#10]
Hi!

I've just tried this colorscheme and have a very small problem. Take the following C code as an example:

![demo](https://github.com/blazkowolf/gruber-darker.nvim/assets/143868321/8f74c09c-68ec-4b4c-8e07-f8973a5e8ebe)

Some keywords are bold while others are not, that seems a little bit weird to me. And I believe it was because `Statement`'s are not default to bold. 

https://github.com/blazkowolf/gruber-darker.nvim/blob/3d1bf7f9f112e70e8123e1d5b85a8df2ffeca93e/lua/gruber-darker/highlights/vim.lua#L185-L192

I'm not sure if such setting is intentional or not, but i think it would be nice to have all keywords highlighted in a consist way.

Thanks!

**Comment by blazkowolf** [comment]
Hi @Pokryton! Thanks for your interest in the colorscheme. I'll do some digging to see if this is expected behavior based on the original gruber-darker-theme this colorscheme is derived from.

It may take me a bit to get around to it as I've got work and other projects I'm working on simultaneously, but I will get to it.

**Comment by blazkowolf** [comment]
Based on this snippet from the original gruber-darker-theme, looking at `font-lock-builtin-face` and `font-lock-keyword-face`:

https://github.com/rexim/gruber-darker-theme/blob/master/gruber-darker-theme.el#L178-L191

I've decided not to change the `Statement` highlight group based on the value of `font-lock-builtin-face`. I think it's up for debate whether it should be bold or not, so I don't fully reject what you're saying - it makes total sense. 

If I get similar queries from other folks, I will probably change it following your suggestion since I haven't implemented a built-in mechanism to update the theme's highlight groups. It's on my TODO list.

I apologize for the long wait, and no payoff.
