### ISSUE TITLE
Overriding default coloracheme settings

### ISSUE THREAD

**Issue by hitogava** [blazkowolf/gruber-darker.nvim#6]
Hi, i've installed ur colorscheme via packer and i'm trying to disable italics with this code in my init.lua
```
require("gruber-darker").setup ({
    opts = {
    bold = false,
    italic = {
      strings = false,
      comments = false,
    },
  },
})
```
but nothing changes, i really hope u'll answer because i find this theme very good and i don't want to change it

**Comment by blazkowolf** [comment]
Hi! Thank you for your interest, I am just seeing your comment. I apologize, I've been pretty busy lately and haven't had time to devote to the colorscheme. It's certainly not an abandoned project by any means, but it just takes me more time to get around to changes. 

Otherwise, if you have any interest in making changes yourself, I'd love to incorporate a PR!

**Comment by blazkowolf** [comment]
I can try to get around to this in a few days

**Comment by blazkowolf** [comment]
@hitogava I pushed a commit that hopefully addresses your issue. I saw that the treesitter highlight `@comment.documentation` did not account for the `italic.comments` setting in the colorscheme configuration, so I added that in. However, my setup showed that the `italic.strings` setting worked fine. If you can explain/show me any examples of where it is not working for you, that would be helpful.
